import {
  AlertCircle as AlertCircleIcon,
  ArrowRight as ArrowRightIcon,
  Award as AwardIcon,
  BarChart2 as BarChart2Icon,
  Battery as BatteryIcon,
  Bell as BellIcon,
  BookOpen as BookOpenIcon,
  Bookmark as BookmarkIcon,
  Box as BoxIcon,
  Briefcase as BriefcaseIcon,
  Building as BuildingIcon,
  Calendar as CalendarIcon,
  Camera as CameraIcon,
  CheckCircle as CheckCircleIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Clock as ClockIcon,
  Cloud as CloudIcon,
  CreditCard as CreditCardIcon,
  Database as DatabaseIcon,
  DollarSign as DollarSignIcon,
  Download as DownloadIcon,
  Edit3 as Edit3Icon,
  ExternalLink as ExternalLinkIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  FileText as FileTextIcon,
  Filter as FilterIcon,
  Flag as FlagIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  Gift as GiftIcon,
  Globe as GlobeIcon,
  Grid as GridIcon,
  Heart as HeartIcon,
  HelpCircle as HelpCircleIcon,
  Home as HomeIcon,
  Image as ImageIcon,
  Info as InfoIcon,
  Key as KeyIcon,
  Layers as LayersIcon,
  LayoutDashboard as LayoutDashboardIcon,
  Link as LinkIcon,
  List as ListIcon,
  Lock as LockIcon,
  Mail as MailIcon,
  Map as MapIcon,
  MapPin as MapPinIcon,
  Menu as MenuIcon,
  MessageSquare as MessageSquareIcon,
  Mic as MicIcon,
  Monitor as MonitorIcon,
  Moon as MoonIcon,
  MoreHorizontal as MoreHorizontalIcon,
  Music as MusicIcon,
  Package as PackageIcon,
  Phone as PhoneIcon,
  PieChart as PieChartIcon,
  Plus as PlusIcon,
  Power as PowerIcon,
  RefreshCw as RefreshCwIcon,
  Search as SearchIcon,
  Server as ServerIcon,
  Settings as SettingsIcon,
  Shield as ShieldIcon,
  ShoppingCart as ShoppingCartIcon,
  Sliders as SlidersIcon,
  Smartphone as SmartphoneIcon,
  Star as StarIcon,
  Sun as SunIcon,
  Tablet as TabletIcon,
  Tag as TagIcon,
  ThumbsUp as ThumbsUpIcon,
  Trash2 as Trash2Icon,
  TrendingUp as TrendingUpIcon,
  Truck as TruckIcon,
  Unlock as UnlockIcon,
  Upload as UploadIcon,
  User as UserIcon,
  Users as UsersIcon,
  Video as VideoIcon,
  Wifi as WifiIcon,
  XCircle as XCircleIcon,
  Zap as ZapIcon,
} from "@lucide/vue"

/**
 * 常用 lucide 图标。每个图标带中文/拼音搜索别名。
 */
export const iconLibrary = [
  { code: "Home", label: "首页", aliases: ["home", "shouye", "首页"], component: HomeIcon },
  { code: "LayoutDashboard", label: "仪表板", aliases: ["dashboard", "yibiaopan", "gongzuotai"], component: LayoutDashboardIcon },
  { code: "Settings", label: "设置", aliases: ["settings", "config", "shezhi"], component: SettingsIcon },
  { code: "Users", label: "用户群", aliases: ["users", "yonghu", "tuandui"], component: UsersIcon },
  { code: "User", label: "用户", aliases: ["user", "yonghu", "geren"], component: UserIcon },
  { code: "Shield", label: "权限/角色", aliases: ["shield", "role", "quanxian", "juese"], component: ShieldIcon },
  { code: "Folder", label: "文件夹", aliases: ["folder", "wenjianjia", "fenzu"], component: FolderIcon },
  { code: "FolderOpen", label: "打开文件夹", aliases: ["folder", "open", "wenjianjia"], component: FolderOpenIcon },
  { code: "Key", label: "密钥", aliases: ["key", "miyao", "token"], component: KeyIcon },
  { code: "Database", label: "数据库", aliases: ["database", "shujuku", "db"], component: DatabaseIcon },
  { code: "Bell", label: "通知", aliases: ["bell", "tongzhi", "xiaoxi"], component: BellIcon },
  { code: "FileText", label: "文档", aliases: ["file", "document", "wendang"], component: FileTextIcon },
  { code: "Search", label: "搜索", aliases: ["search", "sousuo", "chaxun"], component: SearchIcon },
  { code: "Plus", label: "新增", aliases: ["plus", "add", "xinzeng", "chuangjian"], component: PlusIcon },
  { code: "Edit3", label: "编辑", aliases: ["edit", "bianji", "xiugai"], component: Edit3Icon },
  { code: "Trash2", label: "删除", aliases: ["trash", "delete", "shanchu"], component: Trash2Icon },
  { code: "Eye", label: "显示", aliases: ["eye", "show", "xianshi"], component: EyeIcon },
  { code: "EyeOff", label: "隐藏", aliases: ["eyeoff", "hide", "yincang"], component: EyeOffIcon },
  { code: "Link", label: "链接", aliases: ["link", "lianjie"], component: LinkIcon },
  { code: "Mail", label: "邮件", aliases: ["mail", "email", "youjian"], component: MailIcon },
  { code: "Calendar", label: "日历", aliases: ["calendar", "rili", "riqi"], component: CalendarIcon },
  { code: "Clock", label: "时间", aliases: ["clock", "time", "shijian"], component: ClockIcon },
  { code: "Tag", label: "标签", aliases: ["tag", "biaoqian"], component: TagIcon },
  { code: "MapPin", label: "定位", aliases: ["mappin", "location", "dingwei"], component: MapPinIcon },
  { code: "BarChart2", label: "柱状图", aliases: ["bar", "chart", "tongji", "zhuzhuangtu"], component: BarChart2Icon },
  { code: "PieChart", label: "饼图", aliases: ["pie", "chart", "bingtu"], component: PieChartIcon },
  { code: "TrendingUp", label: "趋势", aliases: ["trend", "qushi", "zengzhang"], component: TrendingUpIcon },
  { code: "Zap", label: "快速", aliases: ["zap", "quick", "kuaisu"], component: ZapIcon },
  { code: "Server", label: "服务器", aliases: ["server", "fuwuqi"], component: ServerIcon },
  { code: "Cloud", label: "云服务", aliases: ["cloud", "yun"], component: CloudIcon },
  { code: "Download", label: "下载", aliases: ["download", "xiazai"], component: DownloadIcon },
  { code: "Upload", label: "上传", aliases: ["upload", "shangchuan"], component: UploadIcon },
  { code: "RefreshCw", label: "刷新", aliases: ["refresh", "shuaxin", "sync"], component: RefreshCwIcon },
  { code: "Lock", label: "锁定", aliases: ["lock", "suoding", "anquan"], component: LockIcon },
  { code: "Unlock", label: "解锁", aliases: ["unlock", "jiesuo"], component: UnlockIcon },
  { code: "MessageSquare", label: "消息", aliases: ["message", "xiaoxi", "duihua"], component: MessageSquareIcon },
  { code: "Phone", label: "电话", aliases: ["phone", "dianhua"], component: PhoneIcon },
  { code: "Globe", label: "全球", aliases: ["globe", "global", "quanqiu"], component: GlobeIcon },
  { code: "Map", label: "地图", aliases: ["map", "ditu"], component: MapIcon },
  { code: "Image", label: "图片", aliases: ["image", "tupian"], component: ImageIcon },
  { code: "Music", label: "音乐", aliases: ["music", "yinyue"], component: MusicIcon },
  { code: "Video", label: "视频", aliases: ["video", "shipin"], component: VideoIcon },
  { code: "Mic", label: "麦克风", aliases: ["mic", "maikefeng", "yuyin"], component: MicIcon },
  { code: "Camera", label: "相机", aliases: ["camera", "xiangji"], component: CameraIcon },
  { code: "Monitor", label: "桌面端", aliases: ["monitor", "desktop", "zhuomian"], component: MonitorIcon },
  { code: "Smartphone", label: "手机", aliases: ["smartphone", "mobile", "shouji"], component: SmartphoneIcon },
  { code: "Tablet", label: "平板", aliases: ["tablet", "pingban"], component: TabletIcon },
  { code: "Wifi", label: "无线网络", aliases: ["wifi", "wuxian", "wangluo"], component: WifiIcon },
  { code: "Battery", label: "电量", aliases: ["battery", "dianliang"], component: BatteryIcon },
  { code: "Power", label: "电源", aliases: ["power", "dianyuan", "kaiguan"], component: PowerIcon },
  { code: "Moon", label: "夜间", aliases: ["moon", "dark", "yejian"], component: MoonIcon },
  { code: "Sun", label: "日间", aliases: ["sun", "light", "rijian"], component: SunIcon },
  { code: "Star", label: "收藏", aliases: ["star", "favorite", "shoucang"], component: StarIcon },
  { code: "Heart", label: "喜欢", aliases: ["heart", "like", "xihuan"], component: HeartIcon },
  { code: "ThumbsUp", label: "点赞", aliases: ["thumbsup", "zan", "dianzan"], component: ThumbsUpIcon },
  { code: "AlertCircle", label: "警告", aliases: ["alert", "warning", "jinggao"], component: AlertCircleIcon },
  { code: "CheckCircle", label: "成功", aliases: ["check", "success", "chenggong"], component: CheckCircleIcon },
  { code: "XCircle", label: "失败", aliases: ["x", "error", "shibai"], component: XCircleIcon },
  { code: "Info", label: "信息", aliases: ["info", "xinxi"], component: InfoIcon },
  { code: "HelpCircle", label: "帮助", aliases: ["help", "bangzhu"], component: HelpCircleIcon },
  { code: "Layers", label: "图层", aliases: ["layers", "tuceng"], component: LayersIcon },
  { code: "Box", label: "盒子", aliases: ["box", "hezi"], component: BoxIcon },
  { code: "Package", label: "包裹", aliases: ["package", "baoguo"], component: PackageIcon },
  { code: "Truck", label: "运输", aliases: ["truck", "yunshu"], component: TruckIcon },
  { code: "DollarSign", label: "金额", aliases: ["dollar", "money", "jine"], component: DollarSignIcon },
  { code: "CreditCard", label: "支付", aliases: ["card", "pay", "zhifu"], component: CreditCardIcon },
  { code: "ShoppingCart", label: "购物车", aliases: ["cart", "gouwuche"], component: ShoppingCartIcon },
  { code: "BookOpen", label: "手册", aliases: ["book", "manual", "shouce"], component: BookOpenIcon },
  { code: "Bookmark", label: "书签", aliases: ["bookmark", "shuqian"], component: BookmarkIcon },
  { code: "Flag", label: "标记", aliases: ["flag", "biaoji"], component: FlagIcon },
  { code: "Award", label: "奖章", aliases: ["award", "jiangzhang"], component: AwardIcon },
  { code: "Gift", label: "礼物", aliases: ["gift", "liwu"], component: GiftIcon },
  { code: "Briefcase", label: "业务", aliases: ["briefcase", "business", "yewu"], component: BriefcaseIcon },
  { code: "Building", label: "组织", aliases: ["building", "zuzhi", "gongsi"], component: BuildingIcon },
  { code: "Menu", label: "菜单", aliases: ["menu", "caidan"], component: MenuIcon },
  { code: "MoreHorizontal", label: "更多", aliases: ["more", "gengduo"], component: MoreHorizontalIcon },
  { code: "ChevronDown", label: "下箭头", aliases: ["down", "xia"], component: ChevronDownIcon },
  { code: "ChevronRight", label: "右箭头", aliases: ["right", "you"], component: ChevronRightIcon },
  { code: "ArrowRight", label: "前进", aliases: ["arrow", "qianjin"], component: ArrowRightIcon },
  { code: "ExternalLink", label: "外链", aliases: ["external", "wailian"], component: ExternalLinkIcon },
  { code: "List", label: "列表", aliases: ["list", "liebiao"], component: ListIcon },
  { code: "Grid", label: "网格", aliases: ["grid", "wangge"], component: GridIcon },
  { code: "Filter", label: "筛选", aliases: ["filter", "shaixuan"], component: FilterIcon },
  { code: "Sliders", label: "调节", aliases: ["sliders", "tiaojie"], component: SlidersIcon },
]

export function getIconComponent(code) {
  if (!code) return null
  return iconLibrary.find((i) => i.code === code)?.component ?? null
}

export function searchIcons(query) {
  const q = (query || "").trim().toLowerCase()
  if (!q) return iconLibrary
  return iconLibrary.filter((i) =>
    i.code.toLowerCase().includes(q) ||
    i.label.includes(q) ||
    i.aliases.some((a) => a.toLowerCase().includes(q)),
  )
}
